config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    resources :posts
  end
  devise_for :users
  root to: 'welcome#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # permissions for every user, even if not logged in
    can :read, :all
    # additional permissions for logged in users (they can manage their blogs)
    can :manage, Blog, user_id: user.id if user.present?
    # additional permissions for logged in users (they can manage their posts)
    can :manage, Post, user_id: user.id if user.present?
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
# frozen_string_literal: true

class Blog < ApplicationRecord
  belongs_to :user
  has_many :posts
  validates :name, presence: true, uniqueness: true
  validates :user, presence: true
  validates_associated :user
  validates :name, length: { maximum: 50 }
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  belongs_to :blog
  validates :title, :body, presence: true
  validates :user, presence: true
  validates_associated :user
  validates :blog, presence: true
  validates_associated :blog
  validates :title, length: { maximum: 255 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :full_name, presence: true
  validates :full_name, length: { maximum: 100 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name])
  end
end

app/controllers/blogs_controller.rb
# frozen_string_literal: true

class BlogsController < ApplicationController
  load_and_authorize_resource only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @blogs = Blog.order('name asc').paginate(page: params[:page], per_page: 20)
  end

  def show; end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user = current_user
    if @blog.save
      redirect_to blog_path(@blog),
                  notice: 'Blog was successfully created.'
    else
      render :new
    end
  end

  def edit
    authorize! :manage, @blog
  end

  def update
    authorize! :manage, @blog
    if @blog.update(blog_params)
      redirect_to blog_path(@blog),
                  notice: 'Blog was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize! :manage, @blog
    if @blog.destroy
      redirect_to blogs_url, notice: 'Blog was successfully deleted.'
    else
      redirect_to blog_path(@blog),
                  notice: 'There was an error deleting the blog.'
    end
  end

  private

  def blog_params
    params.require(:blog).permit(%i[name description])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  load_and_authorize_resource only: %i[show edit update destroy]
  before_action :load_blog, only: %i[new create]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    redirect_to blog_path(params[:blog_id])
  end

  def show; end

  def new
    @post = Post.new
  end

  def edit
    authorize! :manage, @post
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.blog = @blog

    if @post.save
      redirect_to [@blog, @post], notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    authorize! :manage, @post
    if @post.update(post_params)
      redirect_to [@post.blog, @post], notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize! :manage, @post
    @post.destroy
    redirect_to blog_path(@post.blog_id), notice: 'Post was successfully destroyed.'
  end

  private

  def load_blog
    @blog = Blog.find(params[:blog_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]

  def index
    @posts = Post.order('updated_at desc').paginate(per_page: 20, page: params[:page])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_class(type)
    case type.to_sym
    when :notice then 'alert alert-primary'
    when :success then 'alert alert-success'
    when :error then 'alert alert-danger'
    when :alert then 'alert alert-warning'
    end
  end

  def blog_pagination_renderer
    @renderer = Class.new(WillPaginate::ActionView::LinkRenderer) do
      def previous_page
        num = @collection.current_page > 1 && @collection.current_page - 1
        previous_or_next_page(num, @options[:previous_label], 'btn-outline-secondary')
      end

      def next_page
        num = @collection.current_page < total_pages && @collection.current_page + 1
        previous_or_next_page(num, @options[:next_label], 'btn-outline-primary')
      end

      def previous_or_next_page(page, text, classname)
        if page
          link(text, page, class: ' btn ' + classname)
        else
          link(text, '#', class: ' btn disabled ' + classname)
        end
      end
    end
  end

  def blog_pagination(objects)
    if objects.total_pages > 1
      content_tag(:p) do
        concat page_entries_info objects, model: 'blog'
        concat will_paginate(objects, page_links: false, previous_label: 'Previous', next_label: 'Next', class: 'blog-pagination', renderer: blog_pagination_renderer)
      end
    end
  end

  def top_navigation
    content_tag(:div, class: 'nav-scroller py-1 mb-2') do
      content_tag(:nav, class: 'nav d-flex justify-content-between') do
        Blog.order('created_at asc').limit(10).each do |blog|
          concat link_to blog.name, blog_path(blog), class: 'p-2 text-muted'
        end
        concat link_to 'All Blogs', blogs_path, class: 'p-2 text-muted'
      end
    end
  end
end

app/helpers/blogs_helper.rb
# frozen_string_literal: true

module BlogsHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/blogs/_form.html.haml
- if @blog.errors.any?
  #error_explanation
    %h2
      = pluralize(@blog.errors.count, "error")
      prohibited this blog from being saved:
    %ul
      - @blog.errors.full_messages.each do |msg|
        %li= msg

.form-group
  = f.label :name
  %br/
  = f.text_field :name, autofocus: true, class: 'form-control'
.form-group
  = f.label :description
  %br/
  = f.text_area :description, class: 'form-control'

app/views/blogs/edit.html.haml
%h2 Edit Blog

.col-lg-6
  = form_for(@blog) do |f|
    = render partial: 'form', locals: {f: f}
    .actions
      = f.submit "Update", class: 'btn btn-primary'

app/views/blogs/index.html.haml
.row
.col-md-8.blog-main
  %h2.pb-3.mb-4.font-italic.border-bottom
    Blogs

  - @blogs.each do |blog|
    .blog-post
      %h2.blog-post-title= blog.name
      %p.blog-post-meta
        = blog.created_at.strftime('%B %d, %Y') 
        by
        = blog.user.full_name
      = simple_format blog.description

      %p
        = link_to "New Post", new_blog_post_path(blog), class: 'btn btn-sm btn-outline-primary'
        = link_to "View Blog", blog_path(blog), class: 'btn btn-sm btn-outline-secondary'
        - if can?(:manage, blog)
          = link_to "Edit Blog", edit_blog_path(blog), class: 'btn btn-sm btn-outline-secondary'
          = link_to "Delete Blog", blog_path(blog), method: :delete, class: 'btn btn-sm  btn-danger', data: { confirm: 'Are you sure to delete this blog as this will also delete all linked posts?' } 

  = blog_pagination(@blogs)

  = link_to "New Blog", new_blog_path, class: 'btn btn-sm btn-outline-secondary'

app/views/blogs/new.html.haml
%h2 New Blog

.col-lg-6
  = form_for(@blog) do |f|
    = render partial: 'form', locals: {f: f}
    .actions
      = f.submit "Create", class: 'btn btn-primary'

app/views/blogs/show.html.haml
.row
.col-md-8.blog-main
  %h2.pb-3.mb-4.font-italic.border-bottom
    = @blog.name

  .blog-post
    %p.blog-post-meta
      = @blog.created_at.strftime('%B %d, %Y') 
      by
      = @blog.user.full_name
    = simple_format @blog.description
    
    %p
      = link_to "New Post", new_blog_post_path(@blog), class: 'btn btn-sm btn-outline-primary'
      - if can?(:manage, @blog)    
        = link_to "Edit Blog", edit_blog_path(@blog), class: 'btn btn-sm btn-outline-secondary'
        = link_to "Delete Blog", blog_path(@blog), method: :delete, class: 'btn btn-sm  btn-danger', data: { confirm: 'Are you sure to delete this blog as this will also delete all linked posts?' } 

  - if @blog.posts.count > 0
    %h2.pb-3.mb-4.font-italic.border-bottom
      Posts

    - @blog.posts.order("updated_at desc").all.each do |post|
      = render partial: 'posts/post', locals: {post: post, listing: true}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1, shrink-to-fit=no", name: "viewport"}/
    %meta{content: "", name: "description"}/
    %meta{content: "", name: "author"}/
    %title Krumblr
    = csrf_meta_tags
    = csp_meta_tag
    %link{href: "https://fonts.googleapis.com/css?family=Playfair+Display:700,900", rel: "stylesheet"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      %header.blog-header.py-3
        .row.flex-nowrap.justify-content-between.align-items-center
          .col-4.pt-1
            
          .col-4.text-center
            %a.blog-header-logo.text-dark{href: root_path} Krumblr
          .col-4.d-flex.justify-content-end.align-items-center
            - if user_signed_in?
              = link_to "Profile", edit_user_registration_path, class: 'btn btn-sm btn-outline-secondary'
              .or or
              = link_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn btn-sm btn-outline-secondary'
            - else
              %a.btn.btn-sm.btn-outline-secondary{href: new_user_session_path} Sign in
              .or or
              %a.btn.btn-sm.btn-outline-secondary{href: new_user_registration_path} Sign up
      
      = top_navigation          

    %main.container{role: "main"}
      - flash.each do |key, value|
        %div{class: "#{flash_class(key)}", role: 'alert' }
          = value
      = yield
      %br
          
    %footer.blog-footer
      %p
        Krumblr Blog built using
        %a{href: "https://getbootstrap.com/"} Bootstrap
        by
        = succeed "." do
          %a{href: "https://github.com/abdulrauf"} @abdulrauf
      %p
        %a{href: "#"} Back to top
    

app/views/posts/_form.html.haml
- if @post.errors.any?
  #error_explanation
    %h2
      = pluralize(@post.errors.count, "error")
      prohibited this post from being saved:
    %ul
      - @post.errors.full_messages.each do |msg|
        %li= msg

.form-group
  = f.label :title
  %br/
  = f.text_field :title, autofocus: true, class: 'form-control'
.form-group
  = f.label :body
  %br/
  = f.text_area :body, rows: 10, class: 'form-control'

app/views/posts/_post.html.haml
.blog-post
  - if listing ==  true
    %h2.blog-post-title
      = post.title
  %p.blog-post-meta
    = post.updated_at.strftime('%B %d, %Y') 
    by
    = post.user.full_name
    on
    = post.blog.name
  - if listing ==  true
    = simple_format truncate(post.body, length: 300)
  - else
    = simple_format post.body

  %p
    - if listing ==  true
      = link_to "View Post", blog_post_path(blog_id: post.blog_id, id: post.id), class: 'btn btn-sm btn-outline-primary'
    - if can?(:manage, post)
      = link_to "Edit Post", edit_blog_post_path(blog_id: post.blog_id, id: post.id), class: 'btn btn-sm btn-outline-secondary'
      = link_to "Delete Post", blog_post_path(blog_id: post.blog_id, id: post.id), method: :delete, class: 'btn btn-sm  btn-danger', data: { confirm: 'Are you sure?' } 

app/views/posts/edit.html.haml
%h2 Edit Post

.col-lg-6
  = form_for([@post.blog, @post]) do |f|
    = render partial: 'form', locals: {f: f}
    .actions
      = f.submit "Update", class: 'btn btn-primary'

  %br
  = link_to 'Back', blog_path(@post.blog)

app/views/posts/new.html.haml
%h2 New #{@blog.name} Post

.col-lg-6
  = form_for([@blog, @post]) do |f|
    = render partial: 'form', locals: {f: f}
    .actions
      = f.submit "Create", class: 'btn btn-primary'

  %br
  = link_to 'Back', blog_path(@blog)

app/views/posts/show.html.haml
.row
.col-md-8.blog-main
  %h2.pb-3.mb-4.font-italic.border-bottom
    = @post.title

  = render partial: 'post', locals: {post: @post, listing: false}

app/views/welcome/index.html.haml
- @posts.each do |post|
  = render partial: 'posts/post', locals: {post: post, listing: true}